name: BlastPick
version: AE-1.2
main: me.pwnage.bukkit.BlastPick.bpm
author: gnftoxic
description: Tool.
commands:
  bp:
    description: An easy way to clear blocks out of your way.
    usage: /<command> [size]